traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
machine:
  image: sobotaio:latest
  labels:
    - "traefik.backend=machine-echo"
    - "traefik.frontend.rule=Host:$HOST"
    - "traefik.port=80"
